server.port=8080
spring.application.name=gateway-service

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://auth-service
spring.cloud.gateway.routes[o].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[o].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[0].id=employee-service
spring.cloud.gateway.routes[0].uri=lb://employee-service
spring.cloud.gateway.routes[o].predicates[0]=Path=/employee/**
spring.cloud.gateway.routes[o].filters[0]=AuthenticationFilter

spring.cloud.gateway.routes[0].id=department-service
spring.cloud.gateway.routes[0].uri=lb://department-service
spring.cloud.gateway.routes[o].predicates[0]=Path=/department/**
spring.cloud.gateway.routes[o].filters[0]=AuthenticationFilter
